name: Run Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      DEFAULT_USERNAME: ${{ secrets.DEFAULT_USERNAME }}
      DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - uses: cypress-io/github-action@v5
        with:
          browser: chrome

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: 💬 Comment & ❌ Auto-close PR if tests failed
        if: failure() && github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body ":x: Cypress tests failed. This PR is being closed automatically."
          gh pr close ${{ github.event.pull_request.number }}
        continue-on-error: true

      - name: ✅ Auto-merge PR if tests passed
        if: success() && github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Merging PR #${{ github.event.pull_request.number }}..."
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
            -d '{"merge_method": "squash"}'
          echo "PR #${{ github.event.pull_request.number }} merged successfully."
